<?php

namespace Database\Seeders;

use App\Models\Event;
use Illuminate\Database\Seeder;

class EventSeeder extends Seeder
{
    public function run(): void
    {
        // Convention : image => 'events/{slug}.jpg'
        // Dossier physique : storage/app/public/events/
        // URL publique    : /storage/events/{slug}.jpg

        $events = [
            // ─── Passés ─────────────────────────────────────────────────────────
            [
                'titre'            => 'Opération Ti Dèj — Baccalauréat 2024',
                'slug'             => 'ti-dej-bac-2024',
                'image'            => 'events/ti-dej-bac-2024.jpg',
                'description_courte' => 'Distribution de petits-déjeuners équilibrés aux candidats au bac 2024.',
                'description'      => "Madin'Jeunes Ambition était au rendez-vous pour le baccalauréat 2024 avec son opération Madin' Ti Dèj.\n\nPrès de 400 petits-déjeuners ont été distribués devant les lycées de Fort-de-France, composés de fruits frais locaux, jus de fruits et viennoiseries.\n\nMerci aux 25 bénévoles qui ont fait de cette édition un succès !",
                'date_debut'       => '2024-06-18 07:00:00',
                'date_fin'         => '2024-06-18 09:30:00',
                'lieu'             => 'Lycées de Fort-de-France',
                'adresse'          => 'Fort-de-France, Martinique',
                'gratuit'          => true,
                'publie'           => true,
            ],
            [
                'titre'            => 'Forum des Associations 2024',
                'slug'             => 'forum-associations-2024',
                'image'            => 'events/forum-associations-2024.jpg',
                'description_courte' => 'Participation de MJA au Forum des Associations de Fort-de-France.',
                'description'      => "MJA était présente au Forum des Associations de Fort-de-France 2024.\n\nL'occasion de présenter nos projets, de rencontrer de futurs bénévoles et de nouer des partenariats avec d'autres associations locales.",
                'date_debut'       => '2024-09-07 10:00:00',
                'date_fin'         => '2024-09-07 18:00:00',
                'lieu'             => 'Parc de la Savane',
                'adresse'          => 'Fort-de-France, Martinique',
                'gratuit'          => true,
                'publie'           => true,
            ],
            [
                'titre'            => 'Atelier Parentalité & Jeunesse',
                'slug'             => 'atelier-parentalite-jeunesse-2025',
                'image'            => 'events/atelier-parentalite-jeunesse-2025.jpg',
                'description_courte' => 'Atelier de dialogue intergénérationnel entre parents et jeunes de Martinique.',
                'description'      => "Dans le cadre du projet Épanouissement Urbain, MJA a organisé un atelier d'échange entre parents et jeunes.\n\nObjectif : mieux se comprendre, renforcer les liens familiaux et aborder ensemble les défis de la jeunesse martiniquaise contemporaine.\n\nIntervenants : psychologue, éducateur spécialisé, médiateur social.",
                'date_debut'       => '2025-03-22 14:00:00',
                'date_fin'         => '2025-03-22 18:00:00',
                'lieu'             => 'Maison des Jeunes et de la Culture',
                'adresse'          => 'Fort-de-France, Martinique',
                'gratuit'          => true,
                'publie'           => true,
            ],
            [
                'titre'            => 'Fwi Ti Dèj — Baccalauréat 2025 (Madin · Karu · Guia)',
                'slug'             => 'fwi-ti-dej-bac-2025',
                'image'            => 'events/fwi-ti-dej-bac-2025.jpg',
                'description_courte' => 'Distribution simultanée de petits-déjeuners dans tous les centres du bac en Martinique, Guadeloupe et Guyane.',
                'description'      => "Le 16 juin 2025, le réseau Fwi Ti Dèj s'est mobilisé simultanément dans trois territoires :\n\n• Madin' Ti Dèj (Martinique) — 8e édition\n• Karu' Ti Dèj (Guadeloupe, Saint-Martin, Marie-Galante) — avec Chemin d'Audace, K2 Esports, Unik Prod\n• Guia' Ti Dèj (Guyane) — avec le CAVL, Graine D'Elie, Maison des Lycéens LP Melkior Garré\n\nPlus de 600 petits-déjeuners distribués gratuitement sur les trois territoires.",
                'date_debut'       => '2025-06-16 07:00:00',
                'date_fin'         => '2025-06-16 09:30:00',
                'lieu'             => "Tous les centres d'examen — Martinique, Guadeloupe, Guyane",
                'adresse'          => 'Fort-de-France, Martinique',
                'gratuit'          => true,
                'publie'           => true,
            ],
            [
                'titre'            => 'Assemblée Générale MJA 2025',
                'slug'             => 'ag-mja-2025',
                'image'            => 'events/ag-mja-2025.jpg',
                'description_courte' => "Assemblée générale annuelle de l'association Madin'Jeunes Ambition.",
                'description'      => "L'Assemblée Générale annuelle de Madin'Jeunes Ambition s'est tenue à Fort-de-France.\n\nTous les membres et sympathisants étaient invités. Au programme : bilan des activités de l'année, présentation des projets à venir, renouvellement du bureau.",
                'date_debut'       => '2025-09-15 18:00:00',
                'lieu'             => 'Siège MJA',
                'adresse'          => '22, passage du Cœur sur la Main, 97200 Fort-de-France',
                'gratuit'          => true,
                'publie'           => true,
            ],
            [
                'titre'            => 'Atelier Santé & Nutrition — Saison 2025',
                'slug'             => 'atelier-sante-nutrition-2025',
                'image'            => 'events/atelier-sante-nutrition-2025.jpg',
                'description_courte' => 'Atelier de sensibilisation à la nutrition et aux bonnes pratiques alimentaires pour les jeunes.',
                'description'      => "Dans le cadre du programme SNS, MJA a organisé un atelier de sensibilisation destiné aux jeunes de 15 à 25 ans.\n\nAu programme : conseils nutritionnels ancrés dans la culture martiniquaise, ateliers pratiques de préparation de repas équilibrés, intervention d'une diététicienne.",
                'date_debut'       => '2025-10-10 14:00:00',
                'date_fin'         => '2025-10-10 17:00:00',
                'lieu'             => 'Maison des Jeunes et de la Culture',
                'adresse'          => 'Fort-de-France, Martinique',
                'gratuit'          => true,
                'lien_inscription' => 'https://www.facebook.com/MadinJeunesAmbition',
                'publie'           => true,
            ],
            [
                'titre'            => 'Forum des Associations 2025',
                'slug'             => 'forum-associations-2025',
                'image'            => 'events/forum-associations-2025.jpg',
                'description_courte' => 'MJA au Forum des Associations 2025 de Fort-de-France.',
                'description'      => "Retrouvez MJA au Forum des Associations de Fort-de-France.\n\nVenez découvrir nos projets, rencontrer notre équipe et rejoindre notre réseau de bénévoles. Nous présenterons également le bilan 2025 et les projets 2026.",
                'date_debut'       => '2025-11-08 10:00:00',
                'date_fin'         => '2025-11-08 18:00:00',
                'lieu'             => 'Parc de la Savane',
                'adresse'          => 'Fort-de-France, Martinique',
                'gratuit'          => true,
                'publie'           => true,
            ],
            [
                'titre'            => 'Gala des Trophées Lumina 2025',
                'slug'             => 'trophees-lumina-2025',
                'image'            => 'events/trophees-lumina-2025.jpg',
                'description_courte' => 'Cérémonie de remise des Trophées Lumina 2025, récompensant les jeunes talents martiniquais.',
                'description'      => "La soirée des Trophées Lumina 2025 a réuni plus de 200 personnes pour célébrer les jeunes talents martiniquais.\n\n8 trophées remis dans les catégories : Entrepreneuriat, Culture, Sport, Engagement associatif, Éducation, Innovation, Solidarité et Coup de cœur du jury.",
                'date_debut'       => '2025-12-06 18:30:00',
                'lieu'             => 'Palais des Congrès de Madiana',
                'adresse'          => 'Schoelcher, Martinique',
                'gratuit'          => false,
                'publie'           => true,
            ],
            [
                'titre'            => 'Fwi Ti Dèj — Baccalauréat 2026 (Madin · Karu · Guia)',
                'slug'             => 'fwi-ti-dej-bac-2026',
                'image'            => 'events/fwi-ti-dej-bac-2026.jpg',
                'description_courte' => 'Nouvelle édition simultanée du Fwi Ti Dèj dans les trois territoires ultramarins.',
                'description'      => "Pour la 9e édition en Martinique, le réseau Fwi Ti Dèj s'est de nouveau mobilisé le 16 juin 2026, matin de l'épreuve de philosophie du bac.\n\nMadin' Ti Dèj, Karu' Ti Dèj et Guia' Ti Dèj ont agi de concert pour distribuer petits-déjeuners et messages de prévention à des centaines de candidats ultramarins.",
                'date_debut'       => '2026-06-16 07:00:00',
                'date_fin'         => '2026-06-16 09:30:00',
                'lieu'             => "Tous les centres d'examen — Martinique, Guadeloupe, Guyane",
                'adresse'          => 'Fort-de-France, Martinique',
                'gratuit'          => true,
                'publie'           => true,
            ],

            // ─── À venir ────────────────────────────────────────────────────────
            [
                'titre'            => 'MJA Sport Day 2026',
                'slug'             => 'mja-sport-day-2026',
                'image'            => 'events/mja-sport-day-2026.jpg',
                'description_courte' => 'Grande journée sportive ouverte à tous les jeunes de la Martinique.',
                'description'      => "Le MJA Sport Day est l'événement sportif de l'année organisé par Madin'Jeunes Ambition.\n\nAu programme : activités variées (football, basketball, athlétisme, natation), ateliers bien-être, démonstrations de sports de combat.\n\nOuvert à tous les jeunes de 12 à 30 ans. Inscription recommandée.",
                'date_debut'       => '2026-07-11 08:00:00',
                'date_fin'         => '2026-07-11 17:00:00',
                'lieu'             => 'Stade Pierre-Aliker',
                'adresse'          => 'Fort-de-France, Martinique',
                'gratuit'          => true,
                'lien_inscription' => 'https://www.facebook.com/MadinJeunesAmbition',
                'publie'           => true,
            ],
            [
                'titre'            => 'Atelier Cuisine Saine Martiniquaise',
                'slug'             => 'atelier-cuisine-saine-aout-2026',
                'image'            => 'events/atelier-cuisine-saine-aout-2026.jpg',
                'description_courte' => 'Atelier de cuisine créole saine : valoriser les légumes locaux et les recettes traditionnelles équilibrées.',
                'description'      => "Dans le cadre du programme Nutrition du SNS, MJA organise un atelier cuisine destiné aux jeunes.\n\nObjectif : redécouvrir les légumes locaux (christophines, ignames, patates douces) et préparer des recettes créoles équilibrées.\n\nPlaces limitées à 20 participants. Inscription obligatoire.",
                'date_debut'       => '2026-08-19 10:00:00',
                'date_fin'         => '2026-08-19 13:00:00',
                'lieu'             => 'Marché couvert de Fort-de-France',
                'adresse'          => 'Fort-de-France, Martinique',
                'gratuit'          => true,
                'lien_inscription' => 'https://www.facebook.com/MadinJeunesAmbition',
                'publie'           => true,
            ],
            [
                'titre'            => 'Assemblée Générale MJA 2026',
                'slug'             => 'ag-mja-2026',
                'image'            => 'events/ag-mja-2026.jpg',
                'description_courte' => "Assemblée générale annuelle de l'association — bilan, projets et renouvellement du bureau.",
                'description'      => "L'Assemblée Générale annuelle de Madin'Jeunes Ambition se tiendra à Fort-de-France.\n\nTous les membres et sympathisants sont invités. Au programme : bilan 2026, plan d'action 2027, élection du nouveau bureau.\n\nAccueil dès 17h30. Buffet offert après la séance.",
                'date_debut'       => '2026-09-19 18:00:00',
                'lieu'             => 'Siège MJA',
                'adresse'          => '22, passage du Cœur sur la Main, 97200 Fort-de-France',
                'gratuit'          => true,
                'publie'           => true,
            ],
            [
                'titre'            => 'Forum de la Jeunesse Martiniquaise 2026',
                'slug'             => 'forum-jeunesse-martiniquaise-2026',
                'image'            => 'events/forum-jeunesse-martiniquaise-2026.jpg',
                'description_courte' => 'Grand forum de la jeunesse martiniquaise : emploi, entrepreneuriat, culture et engagement citoyen.',
                'description'      => "Madin'Jeunes Ambition co-organise le Forum de la Jeunesse Martiniquaise 2026.\n\nThématiques : insertion professionnelle, entrepreneuriat, culture, engagement associatif et citoyen.\n\nAu programme : conférences inspirantes, ateliers pratiques, stands d'associations, networking.",
                'date_debut'       => '2026-10-17 09:00:00',
                'date_fin'         => '2026-10-17 18:00:00',
                'lieu'             => 'Palais des Congrès de Madiana',
                'adresse'          => 'Schoelcher, Martinique',
                'gratuit'          => true,
                'lien_inscription' => 'https://www.facebook.com/MadinJeunesAmbition',
                'publie'           => true,
            ],
            [
                'titre'            => 'Gala des Trophées Lumina 2026',
                'slug'             => 'trophees-lumina-2026',
                'image'            => 'events/trophees-lumina-2026.jpg',
                'description_courte' => 'Cérémonie de remise des Trophées Lumina 2026, récompensant les jeunes talents martiniquais.',
                'description'      => "La grande soirée Trophées Lumina revient pour une nouvelle édition de prestige !\n\nCatégories : Entrepreneuriat · Culture · Sport · Engagement · Éducation · Innovation · Solidarité · Coup de cœur.\n\nProgramme : cocktail dînatoire, remise des trophées, soirée musicale.",
                'date_debut'       => '2026-12-05 18:30:00',
                'lieu'             => 'Palais des Congrès de Madiana',
                'adresse'          => 'Schoelcher, Martinique',
                'gratuit'          => false,
                'publie'           => true,
            ],
            [
                'titre'            => 'Workshop Orientation & CV 2027',
                'slug'             => 'workshop-orientation-cv-2027',
                'image'            => 'events/workshop-orientation-cv-2027.jpg',
                'description_courte' => "Atelier pratique d'orientation professionnelle et rédaction de CV pour les jeunes martiniquais.",
                'description'      => "MJA organise un workshop intensif pour aider les jeunes à préparer leur entrée dans le monde professionnel.\n\nAu programme : techniques CV, lettre de motivation, simulation d'entretien, aides à l'emploi en Martinique.\n\nAnimé par des professionnels RH locaux. Places limitées.",
                'date_debut'       => '2027-02-13 09:00:00',
                'date_fin'         => '2027-02-13 17:00:00',
                'lieu'             => 'Maison des Jeunes et de la Culture',
                'adresse'          => 'Fort-de-France, Martinique',
                'gratuit'          => true,
                'lien_inscription' => 'https://www.facebook.com/MadinJeunesAmbition',
                'publie'           => true,
            ],
            [
                'titre'            => 'Course Solidaire MJA 2027',
                'slug'             => 'course-solidaire-mja-2027',
                'image'            => 'events/course-solidaire-mja-2027.jpg',
                'description_courte' => 'Course solidaire au profit des projets MJA — ouverte à tous, 5 km et 10 km.',
                'description'      => "La Course Solidaire MJA est un événement sportif et caritatif ouvert à tous.\n\n5 km pour les novices, 10 km pour les sportifs, animations, tombola et village santé.\n\nLes fonds financent directement les projets SNS de l'association.\n\nInscription ouverte à partir de 12 ans.",
                'date_debut'       => '2027-04-03 07:30:00',
                'lieu'             => 'Front de mer de Fort-de-France',
                'adresse'          => 'Fort-de-France, Martinique',
                'gratuit'          => false,
                'lien_inscription' => 'https://www.facebook.com/MadinJeunesAmbition',
                'publie'           => true,
            ],
        ];

        foreach ($events as $event) {
            Event::updateOrCreate(['slug' => $event['slug']], $event);
        }
    }
}
